### ISSUE TITLE
Fixed broken links for section 4 content pages

### ISSUE THREAD

**Issue by GT-ACC-RT** [OWASP/OWASP-Testing-Guide-v5#70] opened 2019-07-08 09:33 UTC
Restored broken links in the content page markdown files under each of the testing categories in section 4.

**Comment by kingthorin** [comment] 2019-07-08 09:37
Duplicate of https://github.com/OWASP/OWASP-Testing-Guide-v5/issues/10

**Comment by kingthorin** [comment] 2019-07-19 13:23
Closed in: https://github.com/OWASP/OWASP-Testing-Guide-v5/pull/71

**Closed by kingthorin** 2019-07-19 13:23 UTC
Labels: QA/Edit, duplicate
